In [46]:
# Course ID:- CS-513A
# Course Instructor:- Khashayar Dehnad
# Name:- Dev Satapara
# CWID:- 20021369
# Assignment Brief:- Performed Random Forest Methodology to develop a classification model for given dataset.

In [47]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [48]:
header_names = ["SampleCode", "ClumpThickness", "UniformityCellSize", "UniformityCellShape", "MarginalAdhesion", "SingleEpithelialCellSize", "BareNuclei", "BlandChromatin", "NormalNucleoli", "Mitoses", "Class"]

In [49]:
df =  pd.read_csv('breast-cancer-wisconsin.csv',header=None,skiprows=1, names=header_names,na_values='?')
df

,SampleCode,ClumpThickness,UniformityCellSize,UniformityCellShape,MarginalAdhesion,SingleEpithelialCellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1.0,3,1,1,2
1,1002945,5,4,4,5,7,10.0,3,2,1,2
2,1015425,3,1,1,1,2,2.0,3,1,1,2
3,1016277,6,8,8,1,3,4.0,3,7,1,2
4,1017023,4,1,1,3,2,1.0,3,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2.0,1,1,1,2
695,841769,2,1,1,1,2,1.0,1,1,1,2
696,888820,5,10,10,3,7,3.0,8,10,2,4
697,897471,4,8,6,4,3,4.0,10,6,1,4
698,897471,4,8,8,5,4,5.0,10,4,1,4

In [50]:
df.dropna(axis=0,inplace=True)

In [51]:
df['Class'] = df['Class'].map({2: 'Benign', 4: 'Malignant'}).fillna(df['Class'])
df

,SampleCode,ClumpThickness,UniformityCellSize,UniformityCellShape,MarginalAdhesion,SingleEpithelialCellSize,BareNuclei,BlandChromatin,NormalNucleoli,Mitoses,Class
0,1000025,5,1,1,1,2,1.0,3,1,1,Benign
1,1002945,5,4,4,5,7,10.0,3,2,1,Benign
2,1015425,3,1,1,1,2,2.0,3,1,1,Benign
3,1016277,6,8,8,1,3,4.0,3,7,1,Benign
4,1017023,4,1,1,3,2,1.0,3,1,1,Benign
...,...,...,...,...,...,...,...,...,...,...,...
694,776715,3,1,1,1,3,2.0,1,1,1,Benign
695,841769,2,1,1,1,2,1.0,1,1,1,Benign
696,888820,5,10,10,3,7,3.0,8,10,2,Malignant
697,897471,4,8,6,4,3,4.0,10,6,1,Malignant
698,897471,4,8,8,5,4,5.0,10,4,1,Malignant

In [52]:
X = df.drop(columns=['SampleCode', 'Class'])
y = df['Class']

In [53]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [54]:
RF = RandomForestClassifier()
RF = RF.fit(X_train,y_train)

y_pred = RF.predict(X_test)

In [55]:
accuracy = accuracy_score(y_test, y_pred)*100
print(accuracy)

96.58536585365853

In [56]:
print(pd.Series(RF.feature_importances_,index=X.columns))

ClumpThickness              0.045047
UniformityCellSize          0.269536
UniformityCellShape         0.187851
MarginalAdhesion            0.047110
SingleEpithelialCellSize    0.060024
BareNuclei                  0.138536
BlandChromatin              0.133644
NormalNucleoli              0.106745
Mitoses                     0.011505
dtype: float64